//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpoAppl.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ExpoApplDBEntities : DbContext
    {
        public ExpoApplDBEntities()
            : base("name=ExpoApplDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pricing> Pricings { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
    
        public virtual ObjectResult<proc_DetailsTablewithProdID_Result> proc_DetailsTablewithProdID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_DetailsTablewithProdID_Result>("proc_DetailsTablewithProdID", idParameter);
        }
    
        public virtual ObjectResult<proc_DetailsTablewithSupplierID_Result> proc_DetailsTablewithSupplierID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_DetailsTablewithSupplierID_Result>("proc_DetailsTablewithSupplierID", idParameter);
        }
    
        public virtual ObjectResult<proc_DetailsTablewithSupplierAndProdIDs_Result> proc_DetailsTablewithSupplierAndProdIDs(Nullable<int> pid, Nullable<int> sid)
        {
            var pidParameter = pid.HasValue ?
                new ObjectParameter("pid", pid) :
                new ObjectParameter("pid", typeof(int));
    
            var sidParameter = sid.HasValue ?
                new ObjectParameter("sid", sid) :
                new ObjectParameter("sid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_DetailsTablewithSupplierAndProdIDs_Result>("proc_DetailsTablewithSupplierAndProdIDs", pidParameter, sidParameter);
        }
    }
}
