//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpoAppl.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pricing
    {
        public int PricingID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
