//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpoAppl.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Pricings = new HashSet<Pricing>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
    
        public virtual ICollection<Pricing> Pricings { get; set; }
    }
}
